name: scrumpoker
description: ScrumPoker
version: 1.0.1+2
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Minhas dependências
  http: ^0.13.1
  shared_preferences: ^2.0.5
  connectivity: ^3.0.3
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.1.0
  image_picker: ^0.7.3
  provider: ^5.0.0
  responsive_grid: ^2.2.0
  cached_network_image: ^3.2.3
  auth_buttons: ^3.0.0
  share_plus: ^6.3.0
  clipboard: ^0.1.3
  flutter_speed_dial: ^6.2.0
  google_sign_in_web: ^0.10.2
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/imagens/
    - assets/imagens/scrumpoker_icon.png
    - assets/imagens/scrumpoker_icon_grande.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700

flutter_native_splash:
  image: "assets/imagens/scrumpoker_icon_grande.png"
  color: "ffffff"
  android_disable_fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imagens/scrumpoker_icon_grande.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/imagens/scrumpoker_icon_grande.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/imagens/scrumpoker_icon_grande.png"