name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Dependencies
      - run: flutter pub get

      # Cria um diretório 'private' e decodifica o services.tar.gpg
      - name: Build
        run: |
          mkdir $HOME/private
          gpg --quiet --batch --yes --decrypt --passphrase="$FIREBASE_SECRET" \
          --output $HOME/private/services.tar services.tar.gpg
          tar xvf $HOME/private/services.tar
          flutter build appbundle
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
